spring.application.name=authentication-service
server.port=8081
jwt.secret=NDQ1Mjc1Mzg1OTU1NjQ1MzY1NDQxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000